// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzHKsmvxXu3WwYXOQ17s3G-O1s484SUkA',
    appId: '1:842447671811:web:731568712f550d1828f436',
    messagingSenderId: '842447671811',
    projectId: 'pika-master-d5421',
    authDomain: 'pika-master-d5421.firebaseapp.com',
    storageBucket: 'pika-master-d5421.firebasestorage.app',
    measurementId: 'G-726RE6KKCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn2EhjnHOd-yd_d1cq4s8YqiL1d3lQaXs',
    appId: '1:842447671811:android:d18eceaaedd1ac0e28f436',
    messagingSenderId: '842447671811',
    projectId: 'pika-master-d5421',
    storageBucket: 'pika-master-d5421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7BoanMdG7tjDhnOarLJVhSXMhhRr8sRQ',
    appId: '1:842447671811:ios:1264e85a3240eeb228f436',
    messagingSenderId: '842447671811',
    projectId: 'pika-master-d5421',
    storageBucket: 'pika-master-d5421.firebasestorage.app',
    iosBundleId: 'com.example.pikaMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7BoanMdG7tjDhnOarLJVhSXMhhRr8sRQ',
    appId: '1:842447671811:ios:1264e85a3240eeb228f436',
    messagingSenderId: '842447671811',
    projectId: 'pika-master-d5421',
    storageBucket: 'pika-master-d5421.firebasestorage.app',
    iosBundleId: 'com.example.pikaMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzHKsmvxXu3WwYXOQ17s3G-O1s484SUkA',
    appId: '1:842447671811:web:172bea57bed50d0b28f436',
    messagingSenderId: '842447671811',
    projectId: 'pika-master-d5421',
    authDomain: 'pika-master-d5421.firebaseapp.com',
    storageBucket: 'pika-master-d5421.firebasestorage.app',
    measurementId: 'G-29ERV3ZZ8T',
  );
}
